Comment out master branch failure step
Comment out the step that fails on the master branch.

diff --git a/.github/workflows/update-changelog.yml b/.github/workflows/update-changelog.yml
--- a/.github/workflows/update-changelog.yml
+++ b/.github/workflows/update-changelog.yml
@@ -14,21 +14,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Fail if we are attempting to run on the master branch
-      if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'space-wizards/space-station-14'}}
-      run: exit 1
+#    - name: Fail if we are attempting to run on the master branch
+#      if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'space-wizards/space-station-14'}}
+#      run: exit 1
 
     - name: Install dependencies
       run: sudo apt-get install -y python3-paramiko python3-lxml
-
-    - uses: actions/checkout@v4.2.2
-      with:
-        submodules: 'recursive'
-    - name: Setup .NET Core
-      uses: actions/setup-dotnet@v4.1.0
-      with:
-        dotnet-version: 9.0.x
-
+      
     - name: Publish changelog (Discord)
       continue-on-error: true
       run: Tools/actions_changelogs_since_last_run.py
